server:
  port: 8094

spring:
  application:
   name: service-autodeliver
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.131.6:8848,172.16.131.6:8849,172.16.131.6:8850

logging:
  file:
    path: logs/${spring.application.name}/
  level:
    com.lagou.edu.controller.service.ResumeServiceFeignClient: debug
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

management:
  endpoints:
   web:
    exposure:
      # springboot中暴露健康检查等断点接口 http://localhost:8090/actuator/health
     include: '*'
   health:
     # 暴露健康接口的细节
     show-details: always