server:
  port: 80
spring:
  application:
    name: login
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.131.6:8848 # ,172.16.131.6:8849,172.16.131.6:8850
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 # sentinel dashboard/console 地址
        port: 8719   # sentinel会在该端口启动http server，那么这样的话，控制台定义的一些限流等规则才能发送传递过来，
        # 如果8719端口被占用，那么会依次+1

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    # 订阅服务提供方的应用列表，订阅多个服务提供者使用 "," 连接
    subscribed-services: login-provider