server:
  port: 9200
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://ydh.com:8761/eureka,http://ydh2.com:8762/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
spring:
  application:
    name: cloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangdehong/config-repo.git #配置git服务地址
          username: yangdehong #配置git用户名
          password: Ydh199078 #配置git密码
          search-paths:
            - config-repo
      # 读取分支
      label: main
  rabbitmq:
    host: http://172.16.131.9
    port: 5672
    username: guest
    password: guest
#针对的被调用方微服务名称,不加就是全局生效
#lagou-service-resume:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always